# Generated by Django 3.1.7 on 2021-03-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0005_auto_20210319_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='id',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='update_date',
        ),
        migrations.AlterField(
            model_name='notebook',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='title',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
