# Generated by Django 3.1.7 on 2021-03-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0006_auto_20210319_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
    ]
