# Generated by Django 3.1.7 on 2021-03-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0008_auto_20210319_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
    ]
