# Generated by Django 3.1.7 on 2021-03-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0009_auto_20210319_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='plain_note',
            field=models.TextField(blank=True, max_length=1040),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='title',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
