# Generated by Django 3.1.7 on 2021-03-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0012_auto_20210319_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='title',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
