# Generated by Django 3.1.7 on 2021-03-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0013_auto_20210319_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='plain_note',
            field=models.TextField(max_length=1040),
        ),
    ]
